set(CMAKE_PREFIX_PATH /usr/local/lib)
SET(XLNT_INCLUDE_DIR /usr/local/include)
SET(paho-mqtt3c_LIBRARY_DIR /usr/local/lib)
message(opengl_LIBRARY ----- ${paho-mqtt3c_LIBRARIES})
find_path (paho-mqtt3c_INCLUDE_DIR MQTTClient.h )
find_library (paho-mqtt3c_LIBRARIES paho-mqtt3c)
message(paho-mqtt3c1_LIBRARIES ----- ${paho-mqtt3c_LIBRARIES})
message(paho-mqtt3c_INCLUDE_DIR ----- ${paho-mqtt3c_INCLUDE_DIR})
include (FindPackageHandleStandardArgs)
find_package_handle_standard_args (paho-mqtt3c DEFAULT_MSG paho-mqtt3c_LIBRARIES paho-mqtt3c_INCLUDE_DIR)
